api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    collection:
        pagination:
#            enabled: false
#            page_parameter_name: page
            client_enabled: true
            enabled_parameter_name: pagination
            items_per_page: 11
